### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Victorcoll** [SilentSys/SLAM#40]
object reference not set to an instance of an object see errorlog.txt for more please help me

**Comment by 23Link89** [comment]
Same
--------------------5/18/2016 11:16:37 AM--------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at SLAM.Form1.GetFilepath(String ProcessName)
   at SLAM.Form1.PollRelayWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by navihawk** [comment]
Also getting the same error, not allowed to update .NET since Windows 10 blocks reinstallation of .NET 4.5 (Windows features now states the .NET version as 4.6)

--------------------5/23/2016 4:14:10 AM--------------------
System.NullReferenceException: Object reference not set to an instance of an object.
   at SLAM.Form1.GetFilepath(String ProcessName)
   at SLAM.Form1.PollRelayWorker_DoWork(Object sender, DoWorkEventArgs e)

**Comment by SilentSys** [comment]
It seems that SLAM is having issues detecting which processes are running. Give then new "Override folder detection" feature a try.
